### ISSUE TITLE
Missing Fork button

### ISSUE THREAD

**Issue by Jblack017** [learn-co-curriculum/phase-0-pac-3-intro-to-functions#2]

**Comment by lizbur10** [comment]
Hello there! I have checked the page in Canvas and am not able to recreate the issue - I'm seeing the Fork button. It's possible that it was fixed recently and your browser is still displaying a cached version of the page. I'm going to go ahead and close this issue, but if you're still seeing the problem in a few days feel free to reopen it.

Thanks for contributing to the Flatiron School curriculum! 💙
